USE ROLE ACCOUNTADMIN;

-- STORAGE INTEGRATION MEETUP_GDDP_S3
CREATE STORAGE INTEGRATION IF NOT EXISTS MEETUP_GDDP_S3 TYPE = 'EXTERNAL_STAGE',
STORAGE_PROVIDER = 'S3',
ENABLED = TRUE,
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::203918839842:role/snowflake_dcube_partner',
STORAGE_ALLOWED_LOCATIONS = ('s3://st-fbr-landing-euw3-001/');

-- API INTEGRATION MEETUP_GDDP_GIT
CREATE API INTEGRATION IF NOT EXISTS MEETUP_GDDP_GIT API_PROVIDER = 'git_https_api',
API_ALLOWED_PREFIXES = ('https://github.com/dcube/meetup_gddp.git'),
ENABLED = TRUE;

-- EXTERNAL VOLUME MEETUP_GDDP_S3_LAKEHOUSE
CREATE EXTERNAL VOLUME IF NOT EXISTS MEETUP_GDDP_S3_LAKEHOUSE STORAGE_LOCATIONS = (
    (
        NAME = 'S3_BUCKET_LAKE',
        STORAGE_PROVIDER = 'S3',
        STORAGE_BASE_URL = 's3://st-fbr-lake-euw3-001/',
        STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::203918839842:role/snowflake_s3_lakehouse_role',
        STORAGE_AWS_EXTERNAL_ID = 'snowflake_s3_lakehouse_external_id'
    )
);

USE ROLE SYSADMIN;

-- WAREHOUSE MANAGE
CREATE OR ALTER WAREHOUSE MANAGE WAREHOUSE_SIZE = 'XSMALL',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;

-- WAREHOUSE LOAD
CREATE OR ALTER WAREHOUSE LOAD WAREHOUSE_SIZE = 'MEDIUM',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;

-- WAREHOUSE ANALYSIS
CREATE OR ALTER WAREHOUSE ANALYSIS WAREHOUSE_SIZE = 'MEDIUM',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;


-- Create Databases and shemas
CREATE DATABASE IF NOT EXISTS MEETUP_GDDP;
CREATE SCHEMA IF NOT EXISTS MEETUP_GDDP.UTILS;
CREATE SCHEMA IF NOT EXISTS MEETUP_GDDP.TPCH_SF100;
CREATE SCHEMA IF NOT EXISTS MEETUP_GDDP.TPCH_SF100_ICEBERG CATALOG=SNOWFLAKE EXTERNAL_VOLUME;
