resources:
  - type: "WAREHOUSE"
    deploy_role: "SYSADMIN"
    objects:
      - name: "MANAGE"
        properties:
          warehouse_size: "XSMALL"
          max_cluster_count: 1
          auto_suspend: 60
          auto_resume: True
          initially_suspended: True

      - name: "LOAD"
        properties:
          warehouse_size: "MEDIUM"
          max_cluster_count: 1
          auto_suspend: 60
          auto_resume: True
          initially_suspended: True

      - name: "ANALYSIS"
        properties:
          warehouse_size: "MEDIUM"
          max_cluster_count: 1
          auto_suspend: 60
          auto_resume: True
          initially_suspended: True

  - type: "STORAGE INTEGRATION"
    deploy_role: "ACCOUNTADMIN"
    objects:
      - name: "MEETUP_GDDP_S3"
        properties:
          type: "EXTERNAL_STAGE"
          storage_provider: "S3"
          enabled: True
          storage_aws_role_arn: "&{S3_AWS_LANDING_ROLE_ARN}"
          storage_allowed_locations:
            - "&{S3_BUCKET_LANDING}"

  - type: "API INTEGRATION"
    deploy_role: "ACCOUNTADMIN"
    objects:
      - name: "MEETUP_GDDP_GIT"
        properties:
          api_provider: "git_https_api"
          api_allowed_prefixes:
            - "&{GIT_REPO_URI}"
          enabled: True

  - type: "EXTERNAL VOLUME"
    deploy_role: "ACCOUNTADMIN"
    objects:
      - name: "MEETUP_GDDP_S3_LAKEHOUSE"
        properties:
          storage_locations:
            - name: "S3_BUCKET_LAKE"
              storage_provider: "S3"
              storage_base_url: "&{S3_BUCKET_LAKE}"
              storage_aws_role_arn: "&{S3_AWS_LAKE_ROLE_ARN}"
              storage_aws_external_id: "&{S3_AWS_LAKE_EXTERNAL_ID}"
