USE ROLE SYSADMIN;

------------------------------------------------------------------------------
-- manage warehouses for the account
------------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS MANAGE
  WAREHOUSE_SIZE=XSMALL
  MAX_CLUSTER_COUNT=1
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS LOAD
  WAREHOUSE_SIZE=MEDIUM
  MAX_CLUSTER_COUNT=1
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ANALYSIS
  WAREHOUSE_SIZE=MEDIUM
  MAX_CLUSTER_COUNT=1
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE MANAGE;
