USE ROLE ACCOUNTADMIN;

-- STORAGE INTEGRATION &{DOMAIN}_S3
CREATE STORAGE INTEGRATION IF NOT EXISTS &{DOMAIN}_S3 TYPE = 'EXTERNAL_STAGE',
STORAGE_PROVIDER = 'S3',
ENABLED = TRUE,
STORAGE_AWS_ROLE_ARN = '&{S3_LANDING_ROLE_ARN}',
STORAGE_ALLOWED_LOCATIONS = ('&{S3_LANDING_BUCKET}');

-- API INTEGRATION &{DOMAIN}_GIT
CREATE API INTEGRATION IF NOT EXISTS &{DOMAIN}_GIT API_PROVIDER = 'git_https_api',
API_ALLOWED_PREFIXES = ('&{GIT_REPO_URI}'),
ENABLED = TRUE;

-- EXTERNAL VOLUME &{DOMAIN}_S3_LAKEHOUSE
CREATE EXTERNAL VOLUME IF NOT EXISTS &{DOMAIN}_S3_LAKEHOUSE STORAGE_LOCATIONS = (
    (
        NAME = 'S3_BUCKET_LAKE',
        STORAGE_PROVIDER = 'S3',
        STORAGE_BASE_URL = '&{S3_LAKE_BUCKET}',
        STORAGE_AWS_ROLE_ARN = '&{S3_LAKE_ROLE_ARN}',
        STORAGE_AWS_EXTERNAL_ID = '&{S3_LAKE_EXTERNAL_ID}'
    )
);

USE ROLE SYSADMIN;

-- WAREHOUSE MANAGE
CREATE OR ALTER WAREHOUSE MANAGE WAREHOUSE_SIZE = 'XSMALL',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;

-- WAREHOUSE LOAD
CREATE OR ALTER WAREHOUSE LOAD WAREHOUSE_SIZE = 'MEDIUM',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;

-- WAREHOUSE ANALYSIS
CREATE OR ALTER WAREHOUSE ANALYSIS WAREHOUSE_SIZE = 'MEDIUM',
MAX_CLUSTER_COUNT = 1,
AUTO_SUSPEND = 60,
AUTO_RESUME = TRUE,
INITIALLY_SUSPENDED = TRUE;
